echo "              KANN program helper"
echo "=============================================================="
echo "Welcome to use Kazuki Amakawa's Neural NetWork"
echo "Copyright(c) by Kazuki Amakawa, all right reserved"
echo ""
echo "Contact: "
echo "   Github: https://www.github.com/KazukiAmakawa"
echo "   Mail Address: KazukiAmakawa@gmail.com"
echo "   Telegram: https://t.me/KazukiAmakawa"
echo "=============================================================="
echo "Usage"
echo "   make <command>"
echo ""
echo "Commands"
echo "   test     |\tTest the model trained"
echo "   install  |\tInstall and initial the train program"
echo "   clean    |\tDelete all data in I/O and model"
echo "   help     |\tShow this help list"
echo "   train    |\tTrain the model with input data"
echo "   retrain  |\tAdd new data for the given model"
echo ""
echo "=============================================================="
echo ""
