echo "              KANN program helper"
echo "=============================================================="
echo "Welcome to use Kazuki Amakawa's Neural NetWork"
echo "Copyright(c) by Kazuki Amakawa, all right reserved"
echo ""
echo "Contact: "
echo "   Github: https://www.github.com/KazukiAmakawa"
echo "   Mail Address: KazukiAmakawa@gmail.com"
echo "   Telegram: https://t.me/KazukiAmakawa"
echo "=============================================================="
echo "Usage"
echo "   make <command> (p = )"
echo ""
echo "Commands"
echo "   test     |\tTest the model trained"
echo "   install  |\tInstall and initial the train program"
echo "   clean    |\tDelete all data in I/O and model"
echo "   help     |\tShow this help list"
echo "   train    |\tTrain the model with input data"
echo "   retrain  |\tAdd new data for the given model"
echo ""
echo "Parameter p"
echo "   p = 0    |\tThe program will work automatic"
echo "   p = 1    |\tThe program will show the training images"
echo ""
echo "=============================================================="
echo ""
echo "I/O"
echo "Before you set up the system, please determine the parameter"
echo "in 'Setting.py' are completed."
echo ""
echo "=============================================================="
echo ""
echo "Searching infomation, please using '| grep keyword'."
