echo "              KANN program helper"
echo "=================================================================================="
echo "Welcome to use Kazuki Amakawa's Neural NetWork"
echo "Copyright(c) by Kazuki Amakawa, all right reserved"
echo ""
echo "Contact: "
echo "   Github: https://www.github.com/KazukiAmakawa"
echo "   Mail Address: KazukiAmakawa@gmail.com"
echo "   Telegram: https://t.me/KazukiAmakawa"
echo "=================================================================================="
echo "Usage"
echo "   make <command>"
echo ""
echo "Commands"
echo "        |\tTest the training result"
echo "   -h   |\tShow this help list"
echo "   -t   |\tTrain the KANN model with input data"
echo "   -a   |\tAdd new data for the given model"
echo ""
